name: flextras
description: A collection of Flex widgets (Columns and Rows) with additional functionality.
version: 0.0.1+1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
